<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Mage\Testimonials\Block\ListCustomer $block */
?>

<?php if ($block->getPostCollection() && count($block->getPostCollection())): ?>
    <div class="table-wrapper reviews">
        <table class="data table table-reviews" id="my-reviews-table">
            <caption class="table-caption"><?= $block->escapeHtml(__('Product Reviews')) ?></caption>
            <thead>
            <tr>
                <th scope="col" class="col date"><?= $block->escapeHtml(__('Created')) ?></th>
                <th scope="col" class="col description"><?= $block->escapeHtml(__('Review')) ?></th>
                <th scope="col" class="col actions">&nbsp;</th>
            </tr>
            </thead>
            <tbody>

            <?php foreach ($block->getPostCollection() as $post):
                $customerID = $post->getUserId();
                $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
                $customerObj = $objectManager->create('Magento\Customer\Model\Customer')->load($customerID); ?>
                <tr>
                    <td data-th="<?php echo (new DateTime($post->getCreatedAt()))->format('d/m/Y'); ?>" class="col date"><?php echo (new DateTime($post->getCreatedAt()))->format('d/m/Y'); ?></td>
                    <td data-th="<?php echo $post->getPostContent();?>" class="col description">
                        <?php echo $post->getPostContent();?>
                    </td>
                    <td data-th="<?= $block->escapeHtmlAttr(__('Actions')) ?>" class="col actions">
                        <a href="<?= $block->escapeUrl($block->getEditUrl($post)) ?>" class="action more">
                            <span><?= $block->escapeHtml(__('Edit')) ?></span>
                        </a>
                    </td>
                    <td data-th="<?= $block->escapeHtmlAttr(__('Actions')) ?>" class="col actions">
                        <a href="<?= $block->escapeUrl($block->getDeleteUrl($post)) ?>" class="action more">
                            <span><?= $block->escapeHtml(__('Delete')) ?></span>
                        </a>
                    </td>
                </tr>

            <?php endforeach;?>
            </tbody>
        </table>
    </div>
    <?php if ($block->getPagerHtml()): ?>
        <div class="testimonial-pagination">
            <?php echo $block->getPagerHtml(); ?>
        </div>
    <?php endif ?>
<?php else: ?>
    <div class="message info empty"><span><?= $block->escapeHtml(__('You have submitted no testimonials.')) ?></span></div>
<?php endif; ?>


