<?php

/**
 * @var \Mage\Testimonials\Block\Testimonials $block
 */

?>
<div class="testimonials-block">

<h2 class="testimonials-title"><?php echo __('Testimonials') ?></h2>
<?php

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$customerSession = $objectManager->create('Magento\Customer\Model\Session');

if ($customerSession->isLoggedIn()): ?>

    <div class="testimonials-form-wrapper">
        <div class="testimonial-button testimonial-form-button"><?php echo __('Submit your testimonial') ?></div>
        <form method="post" action="<?= $block->getUrl('testimonials/index/store') ?>" data-role="testimonials-form" class="testimonials-form">
            <div class="testimonials-title">
                <?php echo __('Add testimonial') ?>
            </div>
            <input name="form_key" type="hidden" value="<?php echo $block->getFormKey();?>">
            <textarea name="post-content" placeholder="Testimonial text" autofocus></textarea>
            <button class="testimonial-submit" type="submit"><?php echo __('Submit testimonial') ?></button>
        </form>
    </div>
<?php else: ?>
    <div class="testimonials-form-wrapper">
        <div class="testimonial-button testimonial-modal-button"><?php echo __('Submit your testimonial') ?></div>
    </div>

      <div class="login-wrapper">
        <div class="login-container">
            <div class="modal-close"><i class="fa fa-times" aria-hidden="true"></i></div>
            <span class="testimonials-notification">
                    <?php echo __('You must be logged in to leave a testimonials'); ?>
            </span>

            <div class="testimonials-login">
                <a href="<?= $block->escapeUrl($block->getUrl('customer/account/login')); ?>">
                    <?php echo __('Login'); ?>
                </a>
            </div>
        </div>
      </div>


<?php endif ?>
</div>


    <?php foreach ($block->getPostCollection() as $post):
        $customerID = $post->getUserId();
        $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
        $customerObj = $objectManager->create('Magento\Customer\Model\Customer')->load($customerID); ?>
        <div class="testimonials-wrapper">
            <div class="testimonials-customer-info">
                <div class="testimonials-customer-name">
                            <?php echo $customerObj->getName();?>
                </div>
                <div class="testimonials-publish-date">
                            <?php echo (new DateTime($post->getCreatedAt()))->format('d/m/Y'); ?>
                </div>
            </div>
            <div class="testimonials-content">
                <?php echo $post->getPostContent();?>
            </div>
        </div>
    <?php endforeach;?>

    <?php if ($block->getPagerHtml()): ?>
        <div class="testimonial-pagination">
            <?php echo $block->getPagerHtml(); ?>
        </div>
    <?php endif ?>



