<style>
    table {  font-family: arial, sans-serif;  border-collapse: collapse;  width: 100%;  margin-top: 30px;}
    td, th {  border: 1px solid #dddddd;  text-align: left;  padding: 8px;  }
    tr:nth-child(even) { background-color: #dddddd; }
    .post-id{width:2%} .post-name{width:30%}

</style>

<div>

    <div class="testimonial-block">
            <span class="testimonial-alert">
                <?php echo __('You must be logged in to leave a testimonials'); ?>
            </span>
        <div class="testimonial-login">
            <a href="<?= $block->getUrl('/customer/account/login/') ?>">
                <?php echo __('Login'); ?>
            </a>
        </div>
    </div>

    <form method="post" action="<?= $block->getUrl('testimonials/index/store') ?>" data-role="testimonials-form" class="testimonials-form">
        <div class="testimonials-title">
            <?php echo __('Add testimonial') ?>
        </div>
        <input name="form_key" type="hidden" value="<?php echo $block->getFormKey();?>">
        <textarea name="post_content" placeholder="Testimonial text" autofocus></textarea>
        <button class="testimonial-submit" type="submit"><?php echo __('Submit testimonial') ?></button>
    </form>




</div>

<table>
    <tr>
        <th class="post-name">Name</th>
        <th class="post-name">Date</th>
        <th>Content</th>
    </tr>


    <?php
    foreach ($block->getPostCollection() as $post){

        echo '<tr>
                    <td>'.$post->getFirstname().'</td>
                    <td>'.$post->getCustomerLastName().'</td>
                  </tr>';
    }
    ?>

    <?php
    foreach ($block->getPostCollection() as $post){

        echo '<tr>
                    <td>'.$post->getCustomerFirstName().'</td>
                    <td>'.(new DateTime($post->getCreatedAt()))->format('d/m/Y').'</td>
                    <td>'.$post->getPostContent().'</td>
                  </tr>';
    }
    ?>

</table>

